### PR TITLE
Add systemd socket support and switch excepted for FreeBSD

### PR DESCRIPTION
**Pull request by cruelsmith**
* Use `galera::status_check` to switch between xinetd and systemd support
* Rename `status_xinetd_service_name` to `status_service_name`

Contain the rebased changes by @PopiBrossard and @TwizzyDizzy from #176

Breaking change because of:
* `galera::status_check` fails on `Boolean[True]` usage
* Rename `galera::status_xinetd_service_name` to `galera::status_service_name`
* Uses systemd per default and only removes xinetd file which could result in the case that the port is already be used

---

Closes #176

### CODE REVIEW

**Comment by TwizzyDizzy** [comment]
Hi @fraenki - is something blocking this PR or do you need additional information from us?

Cheers
Thomas

**Comment by fraenki** [comment]
Thanks for all the effort you put into this! We really appreciate this contribution. However, it took us some time to look into this... sorry for that.

I've reimplemented this in a backwards-compatible way in https://github.com/markt-de/puppet-galera/commit/975e1886dbcf876176cecc9772ad0f0839b87879. So instead of renaming variables and repurposing existing variables, I've introduced two new variables. Besides that I've enabled the systemd-based status check only on new distributions: RHEL 9+, Debian 12+, Ubuntu 24.04+. All older distributions will keep the xinetd status check (unless configured otherwise).

We still have some open issues on our list before we can issue a new release, but we're getting there...

**Comment by TwizzyDizzy** [comment]
Well... it won't surprise you that this makes us think twice, before contributing in the future. In hindsight we should've also inquired, whether a breaking change is acceptable or not.

From our POV, you should 1) read changelogs and 2) be in control of your data layer to adjust data, where it is needed to accomodate for breaking changes.

Since I (switching from "we" here on purpose) am not really satisfied with your solution we will likely need to implement this in our wrapper code instead of using that part of this module.

Shall we all learn from this to better clarify what is wanted and what is not wanted for PRs.

Cheers
Thomas

**Comment by fraenki** [comment]
Apologies for not communicating this upfront.

I've copied the code from this PR.  It's the systemd-handling that was provided in this PR, and I've only made minor modifications to make it a non-breaking change for most of us.

Although the new systemd-handling is not enabled on older distributions by default, it's pretty easy to enable it using the class parameter:

```
class { 'galera':
  status_check_type => 'systemd',
  ...
```

Of if you're not satisfied with the defaults that this modules provides, then use Hiera (e.g. in your puppet-control repo) to override them:

```
puppet-control> cat data/os/RedHat-8-family.yaml
galera::status_check_type: 'systemd'
```

I'm sorry, I really don't understand the complaint.

**Comment by TwizzyDizzy** [comment]
I have to apologize here: my aggravation was mainly caused by internal stuff (and a tiny bit by the missed communication regarding the backwards-compatibility) and was misdirected towards you. Next time, I will do better.

Cheers
Thomas

**Pull request closed without merging**
